import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getSession } from "@/auth.config";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./Providers/Authprovider";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession();
    return (
        <html lang="en">
            <body className={`${poppins.variable}  antialiased`}>
                <AuthProvider session={session}>{children}</AuthProvider>
            </body>
        </html>
    );
}
